#!/usr/bin/env bun
// Reads dist/ and docs/ and generates src/backend/embeddedAssets.js
// Run after `vite build` and before `bun build --compile`

import fs from 'fs';
import path from 'path';

const MIME_TYPES = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
  '.md': 'text/markdown',
  '.txt': 'text/plain',
  '.map': 'application/json',
  '.webp': 'image/webp',
  '.xml': 'application/xml',
  '.webmanifest': 'application/manifest+json',
};

function walkDir(dir, prefix = '') {
  const entries = [];
  if (!fs.existsSync(dir)) return entries;
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${item.name}` : item.name;
    if (item.isDirectory()) {
      entries.push(...walkDir(path.join(dir, item.name), rel));
    } else {
      entries.push({ rel, abs: path.join(dir, item.name) });
    }
  }
  return entries;
}

const root = path.resolve(import.meta.dir, '..');
const distFiles = walkDir(path.join(root, 'dist'));
const docsFiles = walkDir(path.join(root, 'docs'));

console.log(`Embedding ${distFiles.length} dist files, ${docsFiles.length} docs files`);

let code = '// Auto-generated by scripts/embed-static.js - do not edit\n';
code += 'const assets = new Map();\n\n';

function addFiles(files, prefix) {
  for (const { rel, abs } of files) {
    const buf = fs.readFileSync(abs);
    const b64 = buf.toString('base64');
    const ext = path.extname(rel).toLowerCase();
    const mime = MIME_TYPES[ext] || 'application/octet-stream';
    const key = prefix ? `${prefix}/${rel}` : rel;
    code += `assets.set('${key}', { data: Buffer.from('${b64}', 'base64'), type: '${mime}' });\n`;
  }
}

addFiles(distFiles, 'dist');
addFiles(docsFiles, 'docs');

code += '\nexport default assets;\n';

const outPath = path.join(root, 'src/backend/embeddedAssets.js');
fs.writeFileSync(outPath, code);

const sizeKB = Math.round(fs.statSync(outPath).size / 1024);
console.log(`Generated ${outPath} (${sizeKB} KB)`);
