// Generates a throwaway super-admin login for the Playwright e2e suite.
//
// Writes tests/e2e/.env.e2e (gitignored), which playwright.config.js loads
// into process.env before the dev-server webServer and the auth.setup.js
// test start. This keeps e2e login self-contained: no real credentials are
// read from the developer's own .env, and CI can run the exact same command
// with no secrets configured. Pass E2E_ADMIN_SEED to get a reproducible
// password (useful for debugging a specific run locally); otherwise a fresh
// random one is generated every time.
//
// Copyright (C) 2026 Quantrail™ Data Private Limited
import { writeFileSync, mkdirSync } from "fs";
import { randomBytes } from "crypto";

const CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#%";

// mulberry32 - small deterministic PRNG so a given seed always reproduces the
// same password, without pulling in a dependency for it.
function mulberry32(seed) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function seedToInt(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (Math.imul(h, 31) + str.charCodeAt(i)) | 0;
  return h;
}

function generatePassword() {
  const seed = process.env.E2E_ADMIN_SEED;
  const rand = seed ? mulberry32(seedToInt(seed)) : () => randomBytes(1)[0] / 256;
  let out = "";
  for (let i = 0; i < 24; i++) out += CHARS[Math.floor(rand() * CHARS.length)];
  return out;
}

const username = "e2e_admin";
const password = generatePassword();
// 32+ hex chars, per env.js's own generation hint ("openssl rand -hex 32").
// A fresh random secret per run is fine here: this run's own SQLite data dir
// starts empty (no prior encrypted credentials to lose access to) and gets
// discarded with the rest of the ephemeral env at teardown.
const encryptionSecret = randomBytes(32).toString("hex");

const contents = [
  "# Auto-generated by scripts/gen-e2e-env.mjs - do not edit, do not commit.",
  "# Removed again by scripts/clear-e2e-env.mjs once the e2e run finishes.",
  `SUPER_ADMIN_1=${username}`,
  `SUPER_ADMIN_1_PASSWORD=${password}`,
  "SUPER_ADMIN_1_EMAIL=e2e-admin@chops.local",
  `ENCRYPTION_SECRET=${encryptionSecret}`,
  "DISABLE_ENV_LOGIN=false",
  "",
].join("\n");

mkdirSync("tests/e2e", { recursive: true });
writeFileSync("tests/e2e/.env.e2e", contents);
console.log(`[gen-e2e-env] wrote tests/e2e/.env.e2e for user "${username}"${process.env.E2E_ADMIN_SEED ? " (seeded)" : ""}`);
