#!/usr/bin/env bun
// generate-version.mjs
//
// Writes src/backend/version.generated.js exporting the resolved app version
// (see resolveVersion.mjs) as a literal string constant. This runs at build/
// dev-start time, on a machine that actually has the env var or git checkout
// available - a compiled binary has neither of those on the end user's
// machine, so the version has to be baked in now, not computed at runtime.
//
// Run before starting/building: node scripts/generate-version.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolveVersion } from "./resolveVersion.mjs";

const version = resolveVersion();
const outPath = fileURLToPath(
  new URL("../src/backend/version.generated.js", import.meta.url),
);

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/generate-version.mjs - do not edit by hand.\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n`,
);

console.log(`Generated src/backend/version.generated.js -> ${version}`);
