#!/usr/bin/env bun
// generate-version.mjs
// author - rva, jkr
// Writes src/backend/version.generated.js exporting the resolved app version
// (see resolveVersion.mjs) as a literal string constant. 
// Run before starting/building: node scripts/generate-version.mjs

import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolveVersion } from "./resolveVersion.mjs";

const version = resolveVersion();

// version.json is the single source of truth for the release identity

let info = {};
try {
  info = JSON.parse(
    readFileSync(fileURLToPath(new URL("../version.json", import.meta.url)), "utf8"),
  );
} catch {
  // Building from a tree without version.json: the build string still works.
}

// Derive the display string and the numeric parts from the resolved version, so the API
// output and the backup metadata keep the same shape.
const semver = /^(\d+)\.(\d+)\.(\d+)/.exec(version);
if (semver) {
  info.major = Number(semver[1]);
  info.minor = Number(semver[2]);
  info.patch = Number(semver[3]);
}
info.display = version;

const outPath = fileURLToPath(
  new URL("../src/backend/version.generated.js", import.meta.url),
);

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/generate-version.mjs - do not edit by hand.\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n` +
    `export const VERSION_INFO = ${JSON.stringify(info, null, 2)};\n`,
);

console.log(`Generated src/backend/version.generated.js -> ${version}`);
