#!/usr/bin/env bun
// generate-version.mjs
//
// Writes src/backend/version.generated.js exporting the resolved app version
// (see resolveVersion.mjs) as a literal string constant. This runs at build/
// dev-start time, on a machine that actually has the env var or git checkout
// available - a compiled binary has neither of those on the end user's
// machine, so the version has to be baked in now, not computed at runtime.
//
// Run before starting/building: node scripts/generate-version.mjs
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolveVersion } from "./resolveVersion.mjs";

const version = resolveVersion();

// version.json is the single source of truth for the release identity
// (clickhouseVersion, major/minor/patch, display, codename). It is baked in
// here alongside the build string so /api/version can answer with real fields.
// It previously read these from CLICKHOUSEVERSION / MAJOR / MINOR / ...
// environment variables that nothing sets, and answered with undefined.
let info = {};
try {
  info = JSON.parse(
    readFileSync(fileURLToPath(new URL("../version.json", import.meta.url)), "utf8"),
  );
} catch {
  // Building from a tree without version.json: the build string still works.
}

const outPath = fileURLToPath(
  new URL("../src/backend/version.generated.js", import.meta.url),
);

writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/generate-version.mjs - do not edit by hand.\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n` +
    `export const VERSION_INFO = ${JSON.stringify(info, null, 2)};\n`,
);

console.log(`Generated src/backend/version.generated.js -> ${version}`);
